# Generated by Django 5.2.6 on 2026-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(default='temp_hash', max_length=255),
            preserve_default=False,
        ),
    ]
