# Generated by Django 5.2.13 on 2026-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_emailotp_otp_code_emailotp_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='itemreport',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Location accuracy in meters', null=True),
        ),
    ]
