# Generated by Django 5.2.6 on 2026-04-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_userprofile_phone_number_itemreport_accuracy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
