# Generated by Django 5.2.13 on 2026-05-04 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_emailotp_delete_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreport',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Location accuracy in meters', null=True, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics / Mobile'), ('wallet', 'Wallet / Purse'), ('keys', 'Keys'), ('pet', 'Pet'), ('bag', 'Bag / Luggage'), ('document', 'Important Document'), ('other', 'Other')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='contact_info',
            field=models.TextField(help_text='How can people contact you? (Email/Phone)', verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='item_date',
            field=models.DateField(blank=True, help_text='When was the item lost/found?', null=True, verbose_name='Item Date'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='report_type',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='message',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.itemreport', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
